### ISSUE TITLE
browser-laptop dependencies missing after setup and require manual "npm install" in ./src/browser-laptop

### ISSUE THREAD

**Issue by willy-b** [brave/browser-laptop-bootstrap#11]
(This one is pretty minor.)

**Issue:**
After setting up `brave/browser-laptop-bootstrap` via `npm install`, `npm run init` and `npm run build`,
I tried to start the bootstrapped app via the recommended `npm run start`.

This gave an error suggesting `npm install` had not been run for the `browser-laptop` dependences:
```
$ npm run start
> browser-laptop-bootstrap@0.13.0-pre.3 start /home/willy/projs/git/3rd/brave/browser-laptop-bootstrap2
> node ./scripts/start.js

/home/willy/projs/git/3rd/brave/browser-laptop-bootstrap2/src/out/Release/brave --user-data-dir=brave-development --enable-logging --v=0 /home/willy/projs/git/3rd/brave/browser-laptop-bootstrap2/src/browser-laptop
App threw an error during load
Error: Cannot find module 'immutable'
    at Module._resolveFilename (module.js:472:15)
    at Function.Module._resolveFilename (/home/willy/projs/git/3rd/brave/browser-laptop-bootstrap2/src/out/Release/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/willy/projs/git/3rd/brave/browser-laptop-bootstrap2/src/browser-laptop/js/lib/appUrlUtil.js:5:19)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'immutable'
    at Module._resolveFilename (module.js:472:15)
    at Function.Module._resolveFilename (/home/willy/projs/git/3rd/brave/browser-laptop-bootstrap2/src/out/Release/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/willy/projs/git/3rd/brave/browser-laptop-bootstrap2/src/browser-laptop/js/lib/appUrlUtil.js:5:19)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
```

(Sure enough, this could be manually fixed by going into `./src/browser-laptop` and running `npm install` there before coming back to the root of `browser-laptop-bootstrap` and running `npm run start`.)

**Comment by willy-b** [comment]
For development, it works for me to go into `browser-laptop-bootstrap/src/browser-laptop`, run `npm install` and then `npm run watch` there, and leave that running, and then run `npm run start` from the root `browser-laptop-bootstrap/` directory.

Is that what you folks are doing internally?

**Comment by willy-b** [comment]
nvm, this is in the docs, closing!
