### ISSUE TITLE
Error on build: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop-bootstrap#13]
I experience the error by trying to build:

````
Brave-MacBook-Pro:browser-laptop-bootstrap Suguru$ npm run build

> browser-laptop-bootstrap@0.13.0-pre.3 build /Users/Suguru/browser-laptop-bootstrap
> node ./scripts/build.js

update branding...
building node...
python /Users/Suguru/browser-laptop-bootstrap/src/build/gyp_chromium.py -D target_arch=x64 -D host_arch=x64 -D buildtype=Custom -D component=static_library -Goutput_dir=/Users/Suguru/browser-laptop-bootstrap/src/out /Users/Suguru/browser-laptop-bootstrap/src/electron/vendor/node/node.gyp
Updating projects from gyp files...
Traceback (most recent call last):
  File "../../../build/mac/find_sdk.py", line 90, in <module>
    print main()
  File "../../../build/mac/find_sdk.py", line 58, in main
    sdks = [re.findall('^MacOSX(10\.\d+)\.sdk$', s) for s in os.listdir(sdk_dir)]
OSError: [Errno 2] No such file or directory: '/Library/Developer/CommandLineTools/Platforms/MacOSX.platform/Developer/SDKs'
gyp: Call to 'python ../../../build/mac/find_sdk.py 10.10' returned exit status 1 while in /Users/Suguru/browser-laptop-bootstrap/src/electron/vendor/node/node.gyp.
null
null
````

nodejs 7.3.0 has been installed.

Edit: @darkdh suggested me to install Xcode. I'll try building after installing it

**Comment by luixxiul** [comment]
It seems it works with Xcode :-) I updated the Wiki home page.
