### ISSUE TITLE
npm run init problem

### ISSUE THREAD

**Issue by MaoShultz** [brave/browser-laptop-bootstrap#42]
```
d:\work\browser-laptop-bootstrap>npm run init

> browser-laptop-bootstrap@1.0.0 init d:\work\browser-laptop-bootstrap
> node ./scripts/sync.js --init

git submodule sync
Synchronizing submodule url for 'vendor/depot_tools'
Synchronizing submodule url for 'vendor/jinja'
git submodule update --init --recursive
git clean -fxd
Removing win_tools-2_7_6_bin/
git reset --hard HEAD
HEAD is now at fafa09d Roll recipe dependencies (trivial).
gclient sync --force --nohooks --with_branch_heads
Bootstrapping cipd client for windows-amd64 from https://chrome-infra-packages.appspot.com/client?platform=windows-amd64&version=git_revision:4d19637ec2c3d1efd8c6a1b05285118b786919e2...
Syncing projects: 100% (98/98), done.
git fetch --all --tags
Fetching origin
git clean -f
git reset --hard refs/tags/66.0.3359.170
git fetch --all --tags
Fetching origin
git clean -f
git reset --hard origin/master
git fetch --all --tags
Fetching origin
git clean -f
git reset --hard origin/master
gclient sync --force --nohooks --with_branch_heads
Syncing projects: 100% (98/98), done.
gclient runhooks
Running hooks:  98% (63/64) update_external_binaries
________ running 'd:\work\browser-laptop-bootstrap\vendor\depot_tools\win_tools-2_7_6_bin\python\bin\python.exe src/electron/script/update-external-binaries.py' in 'd:\work\browser-laptop-bootstrap'
Traceback (most recent call last):
  File "src/electron/script/update-external-binaries.py", line 66, in <module>
  File "src/electron/script/update-external-binaries.py", line 32, in main
  File "src/electron/script/update-external-binaries.py", line 50, in download_and_unzip
  File "src/electron/script/update-external-binaries.py", line 61, in download_framework
  File "d:\work\browser-laptop-bootstrap\src\electron\script\lib\util.py", line 81, in download
    web_file = urllib2.urlopen(url)
  File "d:\work\browser-laptop-bootstrap\vendor\depot_tools\win_tools-2_7_6_bin\python\bin\lib\urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "d:\work\browser-laptop-bootstrap\vendor\depot_tools\win_tools-2_7_6_bin\python\bin\lib\urllib2.py", line 410, in open
    response = meth(req, response)
  File "d:\work\browser-laptop-bootstrap\vendor\depot_tools\win_tools-2_7_6_bin\python\bin\lib\urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "d:\work\browser-laptop-bootstrap\vendor\depot_tools\win_tools-2_7_6_bin\python\bin\lib\urllib2.py", line 442, in error
    result = self._call_chain(*args)
  File "d:\work\browser-laptop-bootstrap\vendor\depot_tools\win_tools-2_7_6_bin\python\bin\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "d:\work\browser-laptop-bootstrap\vendor\depot_tools\win_tools-2_7_6_bin\python\bin\lib\urllib2.py", line 629, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "d:\work\browser-laptop-bootstrap\vendor\depot_tools\win_tools-2_7_6_bin\python\bin\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "d:\work\browser-laptop-bootstrap\vendor\depot_tools\win_tools-2_7_6_bin\python\bin\lib\urllib2.py", line 422, in _open
    '_open', req)
  File "d:\work\browser-laptop-bootstrap\vendor\depot_tools\win_tools-2_7_6_bin\python\bin\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "d:\work\browser-laptop-bootstrap\vendor\depot_tools\win_tools-2_7_6_bin\python\bin\lib\urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "d:\work\browser-laptop-bootstrap\vendor\depot_tools\win_tools-2_7_6_bin\python\bin\lib\urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 1] _ssl.c:507: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version>
Error: Command 'd:\\work\\browser-laptop-bootstrap\\vendor\\depot_tools\\win_tools-2_7_6_bin\\python\\bin\\python.exe src/electron/script/update-external-binaries.py' returned non-zero exit status 1 in d:\work\browser-laptop-bootstrap
null
null
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! browser-laptop-bootstrap@1.0.0 init: `node ./scripts/sync.js --init`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the browser-laptop-bootstrap@1.0.0 init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mao\AppData\Roaming\npm-cache\_logs\2018-05-26T16_54_32_248Z-debug.log
```

**Comment by bsclifton** [comment]
@MaoShultz what shell are you using? (cmd.exe? powershell?) per our troubleshooting docs, I'd be sure to either try cmd.exe or Git Bash:
https://github.com/brave/browser-laptop-bootstrap/wiki/Troubleshooting#windows

**Comment by MaoShultz** [comment]
I'm using cmd.exe with vcvarsall.bat

**Comment by mailtokartik1** [comment]
same problem:
windows server 2016, x64, vs2017 community edition, Git bash.
I think it has something to do with Python version which is v2.7.6.
