### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by jkup** [brave/browser-laptop-bootstrap#8]
Hey all!

Trying to build from bootstrap for the first time!

I cloned the repo, ran npm install and ran npm run init which all worked great! However when I go to run npm run build I get:

```
☁  browser-laptop-bootstrap [master] ⚡ npm run build

> browser-laptop-bootstrap@0.13.0-pre.3 build /Users/jkup/workspace/browser-laptop-bootstrap
> node ./scripts/build.js

update branding...
building node...
python /Users/jkup/workspace/browser-laptop-bootstrap/src/build/gyp_chromium.py -D target_arch=x64 -D host_arch=x64 -D buildtype=Custom -D component=static_library -Goutput_dir=/Users/jkup/workspace/browser-laptop-bootstrap/src/out /Users/jkup/workspace/browser-laptop-bootstrap/src/electron/vendor/node/node.gyp
Updating projects from gyp files...
Traceback (most recent call last):
  File "../../../build/mac/find_sdk.py", line 90, in <module>
    print main()
  File "../../../build/mac/find_sdk.py", line 58, in main
    sdks = [re.findall('^MacOSX(10\.\d+)\.sdk$', s) for s in os.listdir(sdk_dir)]
OSError: [Errno 2] No such file or directory: '/Library/Developer/CommandLineTools/Platforms/MacOSX.platform/Developer/SDKs'
gyp: Call to 'python ../../../build/mac/find_sdk.py 10.10' returned exit status 1 while in /Users/jkup/workspace/browser-laptop-bootstrap/src/electron/vendor/node/node.gyp.
null
null
```

I checked the wiki but don't see my error listed. Any ideas?

**Comment by jkup** [comment]
This was fixed by installing xcode! Should I update the Troubleshooting doc to add the errors I was seeing? https://github.com/brave/browser-laptop-bootstrap/wiki/Troubleshooting#common-problems-while-installing

+ @bbondy

**Comment by bsclifton** [comment]
@jkup please do! :smile:

**Comment by jkup** [comment]
Cool! Updated.
